name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-venv

    - name: Set up virtual environment and install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python manage.py test

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy and Restart Application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Task/Task10 || { echo "Directory not found"; exit 1; }

          # Set up a virtual environment and activate it
          python3 -m venv /home/ubuntu/Task/Task10/venv
          source /home/ubuntu/Task/Task10/venv/bin/activate

          # Install dependencies
          pip install --upgrade pip
          pip install -r /home/ubuntu/Task/Task10/requirements.txt

          # Apply database migrations
          python /home/ubuntu/Task/Task10/manage.py migrate

          # Collect static files
          python /home/ubuntu/Task/Task10/manage.py collectstatic --noinput

          # Build the Docker image
          docker build -t django-app /home/ubuntu/Task/Task10

          # Stop and remove the old container if it exists
          docker stop django-app-container || true
          docker rm django-app-container || true

          # Run the new Docker container
          docker run -d -p 80:8000 --name django-app-container django-app
        EOF
