name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test the application
      run: python -m unittest discover

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy and Restart Application
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ubuntu/Task/Task10 || { echo "Directory not found"; exit 1; }
          
          # Set up a virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies
          pip install -r requirements.txt

          # Apply database migrations
          python manage.py migrate

          # Collect static files
          python manage.py collectstatic --noinput

          # Restart the application using Docker
          docker build -t django-app .
          docker stop django-app-container || true
          docker rm django-app-container || true
          docker run -d -p 80:8000 --name django-app-container django-app
        EOF
