name: CI/CD Pipeline
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Build Docker Image
      run: |
        docker build -t django-app .

    - name: Push Docker Image to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop and remove the old container if it exists
          docker stop django-app-container || true
          docker rm django-app-container || true

          # Remove any existing image with the same name
          docker rmi django-app || true
        EOF
        docker save django-app | ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "docker load"

    - name: Deploy Docker Container
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Run the new Docker container
          docker run -d -p 80:8000 --name django-app-container django-app
        EOF
